# 文章、词卡、周报测试

# 文章
POST http://localhost:3000/articles HTTP/1.1
PUT http://localhost:3000/articles/:articleId HTTP/1.1
{
	"title": "标题",
	"author": "作者",
	"cover": "lalala.jpg",
	"body": "正文正文正文，很好很好很好"
}

GET http://localhost:3000/articles/:articleId HTTP/1.1
DELETE http://localhost:3000/articles/:articleId HTTP/1.1

GET http://localhost:3000/articles/all HTTP/1.1


# 词卡
POST http://localhost:3000/wordCards HTTP/1.1
PUT http://localhost:3000/wordCards/:word HTTP/1.1
{
	"word": "运维",
	"englishWord": "Ops",
	"cover": "lalalasdf.jpg",
	"content": "嘿都是嘿哈很好很好很好"
}

GET http://localhost:3000/wordCards/:word HTTP/1.1
DELETE http://localhost:3000/wordCards/:word HTTP/1.1

GET http://localhost:3000/wordCards/all HTTP/1.1


# 周报
# 创建周报（仅测试）
POST http://localhost:3000/weeklies HTTP/1.1
{
	"username": "benwwchen",
	"article": "58dcafe9b6e16f62edfd1fcf",
	"words": ["58dcb3580e4e676e0c29807a","58dcb33b0e4e676e0c298079"],
	"stats": {
		"wordCount": "12345",
    	"hitWord": "大佬",
    	"hitWordCount": "54321",
    	"mood": ["1","34","89","0","99","20","66"]
	},
	"featured": [{
    	"question": "58db61c9a17204e9f8072e05",
    	"answer": "58dcb5f1689f346ec5fbef76"
	},{
    	"question": "58db61c9a17204e9f8072e02",
    	"answer": "58dcb60b689f346ec5fbef77"
	},{
    	"question": "58db61c9a17204e9f8072e07",
    	"answer": "58dcb631689f346ec5fbef78"
	}]
}

# 获取最新周报
GET http://localhost:3000/weeklies HTTP/1.1
{
  "code": 200,
  "enmsg": "ok",
  "cnmsg": "成功",
  "data": [
    {
      "_id": "58dcb6dd352cfc6fb997ba1a",
      "username": "benwwchen",
      "article": {
        "_id": "58dcafe9b6e16f62edfd1fcf",
        "title": "标题",
        "author": "作者",
        "cover": "lalala.jpg",
        "body": "正文正文正文，嘿嘿哈安徽很好很好很好",
        "__v": 0,
        "date": "2017-03-30T07:12:41.115Z",
        "tags": []
      },
      "__v": 0,
      "generationDate": "2017-03-30T07:42:21.661Z",
      "featured": [
        {
          "question": {
            "_id": "58db61c9a17204e9f8072e05",
            "__v": 0,
            "content": "无标签测试7",
            "type": "daily",
            "date": "2017-03-29T07:27:05.264Z",
            "tags": [],
            "answers": 1,
            "likes": 0
          },
          "answer": {
            "_id": "58dcb5f1689f346ec5fbef76",
            "questionId": "58db61c9a17204e9f8072e05",
            "type": "daily",
            "content": "我就是这么帅哈哈哈",
            "questionContent": "感觉自己最有魅力的地方？",
            "time": "noon",
            "mood": 75,
            "__v": 0,
            "likes": 0,
            "date": "2017-03-30T07:38:25.465Z",
            "answerer": {
              "username": "benwwchen"
            }
          },
          "_id": "58dcb6dd352cfc6fb997ba1d"
        },
        {
          "question": {
            "_id": "58db61c9a17204e9f8072e02",
            "__v": 0,
            "content": "无标签测试4",
            "type": "daily",
            "date": "2017-03-29T07:27:05.264Z",
            "tags": [],
            "answers": 1,
            "likes": 0
          },
          "answer": {
            "_id": "58dcb60b689f346ec5fbef77",
            "questionId": "58db61c9a17204e9f8072e02",
            "type": "daily",
            "content": "我222222",
            "questionContent": "感觉怎样？",
            "time": "noon",
            "mood": 75,
            "__v": 0,
            "likes": 0,
            "date": "2017-03-30T07:38:51.904Z",
            "answerer": {
              "username": "benwwchen"
            }
          },
          "_id": "58dcb6dd352cfc6fb997ba1c"
        },
        {
          "question": {
            "_id": "58db61c9a17204e9f8072e07",
            "__v": 0,
            "content": "无标签测试9",
            "type": "daily",
            "date": "2017-03-29T07:27:05.264Z",
            "tags": [],
            "answers": 1,
            "likes": 0
          },
          "answer": {
            "_id": "58dcb631689f346ec5fbef78",
            "questionId": "58db61c9a17204e9f8072e07",
            "type": "daily",
            "content": "我333333",
            "questionContent": "感觉怎样啊？",
            "time": "noon",
            "mood": 75,
            "__v": 0,
            "likes": 0,
            "date": "2017-03-30T07:39:29.936Z",
            "answerer": {
              "username": "benwwchen"
            }
          },
          "_id": "58dcb6dd352cfc6fb997ba1b"
        }
      ],
      "stats": {
        "wordCount": 12345,
        "hitWord": "大佬",
        "hitWordCount": 54321,
        "mood": [
          1,
          34,
          89,
          0,
          99,
          20,
          66
        ]
      },
      "words": [
        {
          "_id": "58dcb3580e4e676e0c29807a",
          "word": "运维",
          "englishWord": "Ops",
          "cover": "lalalasdf.jpg",
          "content": "嘿都是嘿哈很好很好很好",
          "__v": 0,
          "tags": []
        },
        {
          "_id": "58dcb33b0e4e676e0c298079",
          "word": "读研",
          "englishWord": "graduate degree",
          "cover": "lalalasdf.jpg",
          "content": "正文正文正d文，嘿都是嘿哈很好很好很好",
          "__v": 0,
          "tags": []
        }
      ]
    }
  ]
}

# 分享周报
PUT http://localhost:3000/weeklies/share/:weeklyId HTTP/1.1
{
    "public": true
}